# server_action.yml
name: 'Server request bot for educational process'
description: 'Send request to server and retrieve logs'
inputs:
  number-of-pr:
    description: 'Number of pull request'
    required: true
    default: '1'
  github-token:
    description: 'Github token'
    required: true
    default: "${{ github.token }}"
  repository-name:
    description: 'Full name of repo. Format: <owner>/<name of repo>'
    required: true
    default: ${{ github.event.repository.full_name }}
  command:
    description: 'Command to run on server'
    required: false
    default: 'check_pr'
  additional-arguments:
    description: 'Additional arguments for the command in JSON format'
    required: false
    default: '{}'

branding:
  icon: 'server'
  color: 'gray-dark'

runs:
  using: 'composite'
  steps:
    - run: |
        COMMAND="${{ inputs.command }}"
        ADDITIONAL_ARGUMENTS="${{ inputs.additional-arguments }}"
        PAYLOAD=$(jq -n --arg command "$COMMAND" --argjson arguments "$(echo $ADDITIONAL_ARGUMENTS)" '{
          command: $command,
          arguments: $arguments
        }')
        RESPONSE=$(curl -X 'POST' \
          "$SERVER_URL/run_command/" \
          -H 'accept: application/json' \
          -H 'Content-Type: application/json' \
          -d "$PAYLOAD")
        echo "$RESPONSE"
      shell: bash
