# action.yml
name: 'Antiplagiarism check'
description: 'Looking for plagiarism in educational repository'
inputs:
  github-token:  
    description: 'Github token'
    required: true
    default: "${{ github.token }}"
  repository-name:
    description: 'Full name of repo. Format.: <owner>/<name of repo>'
    required: true
    default: ${{ github.event.repository.full_name }}

branding:
  icon: 'book'  
  color: 'gray-dark'

runs:
  using: 'composite'
  steps:
    - run: echo "There should be antiplagiarism check"
      shell: bash
