# action.yml
name: 'Pull request bot checker for educational process'
description: 'Check view of pr, such as: name of pr, commits, structure, files and so on'
inputs:
  github-token:  
    description: 'Github token'
    required: true
    default: "${{ github.token }}"
  repository-name:
    description: 'Full name of repo. Format.: <owner>/<name of repo>'
    required: true
    default: ${{ github.event.repository.full_name }}

branding:
  icon: 'book'  
  color: 'gray-dark'

runs:
  using: 'composite'
  shell: bash
  steps:
    - uses: actions/checkout@v2

    - name: Pull docker image
      run: docker pull artanias/codeplag-ubuntu20.04:0.2.8
     
    - name: Clone all branches
      run: |
        git clone "https://github.com/${{ inputs.repository-name }}"
        cd check_plag
        for branch in $(git branch --all | grep '^\s*remotes' | egrep --invert-match '(:?HEAD|main|master)$'); do
            git branch --track "${branch##*/}" "$branch"
        done
   
    - name: Merge all branches
      run: |
        cd check_plag
        git config --global user.email "robot@example.com"
        git config --global user.name "robot"
        git merge $(git branch | tr -s '\r\n*' ' ' | sed -r 's/main//' | sed -r 's/master//') -m "Merge all branches."

    - name: Run plagiarism searching
      run: |
        cd check_plag
        docker run --rm --volume $(pwd):/usr/src/works:ro --volume $(pwd)/reports:/usr/src/reports:rw "artanias/codeplag-ubuntu20.04:0.2.8" /bin/bash -c "codeplag settings modify --reports /usr/src/reports && codeplag check --extension py --directories /usr/src/works/"
   
    - name: Save reports
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: check_plag/reports/
        retention-days: 1
        if-no-files-found: error
