# action.yml
name: 'Linter check'
description: 'Check source code for style coding'
inputs:
  github-token:  
    description: 'Github token'
    required: true
    default: "${{ github.token }}"
  number-of-pr:  
    description: 'Number of pull request'
    required: true
    default: '1'
  repository-name:
    description: 'Full name of repo. Format.: <owner>/<name of repo>'
    required: true
    default: ${{ github.event.repository.full_name }}

branding:
  icon: 'book'  
  color: 'gray-dark'

runs:
  using: 'composite'
  steps:
    - run: echo "There should be linter check"
      shell: bash
