# action.yml
name: 'Pull request bot checker for educational process'
description: 'Check view of pr, such as: name of pr, commits, structure, files and so on'
inputs:
  github-token:  
    description: 'Github token'
    required: true
    default: "${{ github.token }}"
  repository-name:
    description: 'Full name of repo. Format.: <owner>/<name of repo>'
    required: true
    default: ${{ github.event.repository.full_name }}

branding:
  icon: 'book'  
  color: 'gray-dark'

defaults:
  runs:
    shell: bash

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2

    - name: set repo name
      id: repo_name
      shell: bash
      run: |
        REPO_NAME=${{ inputs.repository-name }}
        REPO_NAME=${REPO_NAME##*/}
        echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
        echo "pwd=${pwd}" >> $GITHUB_OUTPUT
        echo "full=${pwd}/$REPO_NAME" >> $GITHUB_OUTPUT

    - name: Pull docker image
      shell: bash
      run: docker pull artanias/codeplag-ubuntu20.04:0.2.8
     
    - name: Clone all branches
      shell: bash
      run: |
        git clone "https://github.com/${{ inputs.repository-name }}"

    - name: Run plagiarism searching
      shell: bash
      run: |
        cd ${{ steps.repo_name.outputs.repo_name }}
        docker run --rm --volume ${{ steps.repo_name.outputs.full }}:/usr/src/works:ro --volume ${{ steps.repo_name.outputs.pwd }}/reports:/usr/src/reports:rw "artanias/codeplag-ubuntu20.04:0.2.8" /bin/bash -c "mkdir -p /usr/src/reports && ls -R /usr/src && codeplag settings modify --reports /usr/src/reports && codeplag check --extension cpp --directories /usr/src/works/"
        ls -R ../
   
    - name: Save reports
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: ${{ steps.repo_name.outputs.pwd }}/reports/
        retention-days: 1
        if-no-files-found: error
