name: update-scheduled-actions

on:
  push:
    paths:
      - schedule.yml

jobs:
  run:
    runs-on: self-hosted
    steps:
      - id: update-scheduled-actions
        name: Update scheduled actions
        run: docker run --rm --network=host -v ${PR_BOT_CONFIG_PATH}:/config mirrin/pr-automation:graduate_machalichev python3.8 generate_scheduled_actions.py /config ${{ github.event.repository.full_name }}
